branch-defaults:
  develop:
    environment: Nd0067c4deploymentprocessprojectstar-env
environment-defaults:
  Nd0067c4deploymentprocessprojectstar-env:
    branch: develop
    repository: origin
global:
  application_name: nd0067-c4-deployment-process-project-starter
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
